<a href="https://colab.research.google.com/github/shafiq73/2024/blob/main/Keggle002_Spaceship_Titanic_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sample_submission.csv to sample_submission (1).csv
Saving SpeaceShip_Titanic_train.csv to SpeaceShip_Titanic_train (1).csv
Saving SpaecShip_Titanic_test.csv to SpaecShip_Titanic_test (1).csv

In [ ]:
df_train = pd.read_csv('SpeaceShip_Titanic_train.csv')
df_test = pd.read_csv('SpaecShip_Titanic_test.csv')
df_test["Transported"] = False
df = pd.concat([df_train, df_test],sort=False)
df.drop(['Name'], axis=1, inplace=True)
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [ ]:
df.shape[0]== df_train.shape[0]+df_test.shape[0]

True

In [ ]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Cabin           299
Destination     274
Age             270
VIP             296
RoomService     263
FoodCourt       289
ShoppingMall    306
Spa             284
VRDeck          268
Transported       0
dtype: int64

In [ ]:
# 1. Split Cabin into 3 columns
df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split('/', expand=True)

# 2. Drop Cabin column
df = df.drop(columns=['Cabin'])  # or df.drop(columns=['Cabin'], inplace=True)

# 3. Replace missing values
df['Deck'] = df['Deck'].fillna('U')
df['Num'] = df['Num'].fillna(-1)
df['Side'] = df['Side'].fillna('U')

In [ ]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Transported', 'Deck', 'Num', 'Side'],
      dtype='object')

In [ ]:
# impute_lis = ['PassengerId', 'HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP','RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',   'Transported', 'Tranported', 'Deck', 'Num', 'Side']
# rest = list(set(df.columns)-set(impute_lis))
# df_rest = df[rest]
# imp = KNNImputer(n_neighbors=5)
# df_imputed = imp.fit_transform(df[impute_lis])
# df_impute = pd.DataFrame(df_imputed, columns=impute_lis)
# df.concat([df_rest, df_impute], axis=1)

In [ ]:
df['Side'].value_counts()

Side
S    6381
P    6290
U     299
Name: count, dtype: int64

In [ ]:
df['Deck'] = df['Deck'].map({'F':0,'G':1,'E':2,'B':3,'C':4, 'D':5,'A':6,'U':7,'T':8})
df['Side'] = df ['Side'].map({'U':-1,'P':1,'S':2})

In [ ]:
from pandas.core.reshape.encoding import get_dummies
# Fill missing values
df['HomePlanet'] = df['HomePlanet'].fillna('U')
df['Destination'] = df['Destination'].fillna('U')

categorical_cols = ['HomePlanet','Destination']
for col in categorical_cols:
    df = pd.concat([df, pd.get_dummies(df[col], prefix = col)],axis=1)
df = df.drop(columns = categorical_cols)

In [ ]:
df.columns

Index(['PassengerId', 'CryoSleep', 'Age', 'VIP', 'RoomService', 'FoodCourt',
       'ShoppingMall', 'Spa', 'VRDeck', 'Transported', 'Deck', 'Num', 'Side',
       'HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars',
       'HomePlanet_U', 'Destination_55 Cancri e', 'Destination_PSO J318.5-22',
       'Destination_TRAPPIST-1e', 'Destination_U'],
      dtype='object')

In [ ]:
# # Fill missing values
# df['HomePlanet'] = df['HomePlanet'].fillna('U')
# df['Destination'] = df['Destination'].fillna('U')

# categorical_cols = ['HomePlanet', 'Destination']

# for col in categorical_cols:
#     dummies = pd.get_dummies(df[col], prefix=col)
#     df = pd.concat([df, dummies], axis=1)

#     print(f"\nOne-hot encoded columns for {col}:")
#     print(dummies.head())   # shows output

In [ ]:
# df.fillna(0, inplace=True)

In [ ]:
from re import A
# feature engineering
bill_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df['am_spent'] = df[bill_cols].sum(axis=1)
df['standard_spent'] = df[bill_cols].std(axis=1)
df['mean_spent'] = df[bill_cols].mean(axis=1)

In [ ]:
# numeric_df = df.select_dtypes(include=['int64', 'float64'])
# numeric_df.corr()

In [ ]:
df.corr()

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,...,HomePlanet_Europa,HomePlanet_Mars,HomePlanet_U,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Destination_U,am_spent,standard_spent,mean_spent
PassengerId,1.000000,-0.003758,-0.013591,0.012376,-0.000886,-0.010844,-0.006561,-0.006324,0.005975,0.014628,...,-0.003572,-0.018262,0.003564,-0.007143,0.015622,-0.003330,-0.000521,-0.006960,-0.011347,-0.006997
CryoSleep,-0.003758,1.000000,-0.065908,-0.079417,-0.259539,-0.214126,-0.221576,-0.206224,-0.195491,0.325803,...,0.103621,0.034422,0.000664,0.069455,0.088941,-0.109418,-0.019006,-0.383651,-0.389980,-0.383023
Age,-0.013591,-0.065908,1.000000,0.082068,0.067300,0.124447,0.034959,0.118992,0.101441,-0.050775,...,0.218231,0.024246,0.002652,0.021579,-0.031337,-0.000539,0.004076,0.179890,0.176188,0.179676
VIP,0.012376,-0.079417,0.082068,1.000000,0.060926,0.128288,0.024289,0.082750,0.113856,-0.018466,...,0.141077,0.044941,-0.000509,0.039858,-0.005552,-0.027851,-0.010412,0.168699,0.156707,0.166622
RoomService,-0.000886,-0.259539,0.067300,0.060926,1.000000,-0.020146,0.057402,0.008936,-0.023847,-0.176328,...,-0.074249,0.254648,-0.005023,-0.023729,-0.061427,0.060421,-0.005982,0.225418,0.220115,0.227306
FoodCourt,-0.010844,-0.214126,0.124447,0.128288,-0.020146,1.000000,-0.001589,0.228990,0.244279,0.036364,...,0.365734,-0.128505,-0.012925,0.131756,-0.062591,-0.071840,-0.011840,0.747820,0.753564,0.743964
ShoppingMall,-0.006561,-0.221576,0.034959,0.024289,0.057402,-0.001589,1.000000,0.010504,0.004485,0.005941,...,-0.032737,0.125744,0.001864,-0.015720,-0.029856,0.032696,-0.001860,0.229435,0.218316,0.229129
Spa,-0.006324,-0.206224,0.118992,0.082750,0.008936,0.228990,0.010504,1.000000,0.149874,-0.156006,...,0.270728,-0.090889,-0.005397,0.088005,-0.053483,-0.043558,0.001770,0.593120,0.543463,0.589076
VRDeck,0.005975,-0.195491,0.101441,0.113856,-0.023847,0.244279,0.004485,0.149874,1.000000,-0.143561,...,0.278988,-0.111368,0.005948,0.088589,-0.043602,-0.047237,-0.007906,0.605014,0.570532,0.615146
Transported,0.014628,0.325803,-0.050775,-0.018466,-0.176328,0.036364,0.005941,-0.156006,-0.143561,1.000000,...,0.131977,0.005643,0.006403,0.083625,0.000760,-0.072731,-0.000554,-0.139225,-0.121017,-0.139777
Deck,-0.008610,0.058245,0.172510,0.147036,0.031689,0.253702,-0.000785,0.185962,0.186894,0.062790,...,0.668231,-0.116363,-0.003120,0.206567,-0.119478,-0.101595,-0.010686,0.297859,0.282270,0.296310
Num,0.665212,-0.040397,-0.134485,-0.090867,-0.010753,-0.175976,-0.007736,-0.130349,-0.133766,-0.035240,...,-0.477100,0.058000,0.007981,-0.144990,0.105792,0.059594,0.001456,-0.207551,-0.196635,-0.206842
Side,-0.000689,0.000853,0.010696,-0.010515,-0.017263,0.008531,-0.011524,-0.002041,0.010163,0.059872,...,0.014239,-0.004209,0.008924,0.009081,-0.008157,-0.004370,0.005035,0.001458,0.004472,0.001207
HomePlanet_Earth,0.016833,-0.116945,-0.207574,-0.157279,-0.141587,-0.205722,-0.074711,-0.156753,-0.150929,-0.119644,...,-0.598448,-0.541683,-0.159801,-0.158758,0.235071,-0.007776,-0.001104,-0.285283,-0.267406,-0.284083
HomePlanet_Europa,-0.003572,0.103621,0.218231,0.141077,-0.074249,0.365734,-0.032737,0.270728,0.278988,0.131977,...,1.000000,-0.288282,-0.085045,0.300618,-0.160735,-0.157244,-0.011508,0.400467,0.377933,0.398938
HomePlanet_Mars,-0.018262,0.034422,0.024246,0.044941,0.254648,-0.128505,0.125744,-0.090889,-0.111368,0.005643,...,-0.288282,1.000000,-0.076979,-0.119349,-0.117632,0.172029,0.013630,-0.068906,-0.066264,-0.068570
HomePlanet_U,0.003564,0.000664,0.002652,-0.000509,-0.005023,-0.012925,0.001864,-0.005397,0.005948,0.006403,...,-0.085045,-0.076979,1.000000,-0.007333,-0.005979,0.010150,-0.000306,-0.007464,-0.009828,-0.008011
Destination_55 Cancri e,-0.007143,0.069455,0.021579,0.039858,-0.023729,0.131756,-0.015720,0.088005,0.088589,0.083625,...,0.300618,-0.119349,-0.007333,1.000000,-0.160268,-0.743879,-0.074284,0.135282,0.130571,0.136424
Destination_PSO J318.5-22,0.015622,0.088941,-0.031337,-0.005552,-0.061427,-0.062591,-0.029856,-0.053483,-0.043602,0.000760,...,-0.160735,-0.117632,-0.005979,-0.160268,1.000000,-0.466273,-0.046562,-0.093571,-0.092951,-0.093318
Destination_TRAPPIST-1e,-0.003330,-0.109418,-0.000539,-0.027851,0.060421,-0.071840,0.032696,-0.043558,-0.047237,-0.072731,...,-0.157244,0.172029,0.010150,-0.743879,-0.466273,1.000000,-0.216117,-0.055845,-0.051743,-0.056944
Destination_U,-0.000521,-0.019006,0.004076,-0.010412,-0.005982,-0.011840,-0.001860,0.001770,-0.007906,-0.000554,...,-0.011508,0.013630,-0.000306,-0.074284,-0.046562,-0.216117,1.000000,-0.010868,-0.012180,-0.011022
am_spent,-0.006960,-0.383651,0.179890,0.168699,0.225418,0.747820,0.229435,0.593120,0.605014,-0.139225,...,0.400467,-0.068906,-0.007464,0.135282,-0.093571,-0.055845,-0.010868,1.000000,0.962495,0.997011
standard_spent,-0.011347,-0.389980,0.176188,0.156707,0.220115,0.753564,0.218316,0.543463,0.570532,-0.121017,...,0.377933,-0.066264,-0.009828,0.130571,-0.092951,-0.051743,-0.012180,0.962495,1.000000,0.962349
mean_spent,-0.006997,-0.383023,0.179676,0.166622,0.227306,0.743964,0.229129,0.589076,0.615146,-0.139777,...,0.398938,-0.068570,-0.008011,0.136424,-0.093318,-0.056944,-0.011022,0.997011,0.962349,1.000000

In [ ]:
df.corr()['Transported'].sort_values(ascending=False)

Transported                  1.000000
CryoSleep                    0.325803
HomePlanet_Europa            0.131977
Destination_55 Cancri e      0.083625
Deck                         0.062790
Side                         0.059872
FoodCourt                    0.036364
PassengerId                  0.014628
HomePlanet_U                 0.006403
ShoppingMall                 0.005941
HomePlanet_Mars              0.005643
Destination_PSO J318.5-22    0.000760
Destination_U               -0.000554
VIP                         -0.018466
Num                         -0.035240
Age                         -0.050775
Destination_TRAPPIST-1e     -0.072731
HomePlanet_Earth            -0.119644
standard_spent              -0.121017
am_spent                    -0.139225
mean_spent                  -0.139777
VRDeck                      -0.143561
Spa                         -0.156006
RoomService                 -0.176328
Name: Transported, dtype: float64

In [ ]:
# df.select_dtypes(include='object').columns

In [ ]:
# df.dtypes

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df_train.drop(columns=['Transported'])
y = df_train['Transported']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
df_train, df_test = df[:df_train.shape[0]], df[df_train.shape[0]:]
df_test = df_test.drop(columns=['Transported'])
df_train.shape, df_test.shape

((8693, 24), (4277, 23))

In [ ]:
X_train = X_train.astype(float)
X_test  = X_test.astype(float)

In [ ]:
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
model_1 = LogisticRegression()
model_2 = DecisionTreeClassifier()
model_3 = RandomForestClassifier()
model_4 = XGBClassifier()
model_5 = LGBMClassifier()

In [ ]:
y_train = y_train.astype(int)
y_test  = y_test.astype(int)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Define the model
model_1 = RandomForestClassifier(
    n_estimators=300,
    random_state=42)

In [ ]:
X_train.dtypes[X_train.dtypes == 'object']

PassengerId    object
CryoSleep      object
VIP            object
Num            object
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

X = df_train.drop(columns=['Transported'])
y = df_train['Transported'].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
X_train = X_train.select_dtypes(exclude=['object'])
X_test  = X_test[X_train.columns]  # align columns

In [ ]:
categorical_cols = X_train.select_dtypes(include=['object']).columns

for col in categorical_cols:
    X_train = pd.concat([X_train, pd.get_dummies(X_train[col], prefix=col)], axis=1)
    X_test  = pd.concat([X_test, pd.get_dummies(X_test[col], prefix=col)], axis=1)

# Drop original object columns
X_train = X_train.drop(columns=categorical_cols)
X_test  = X_test[X_train.columns]  # ensure same columns

In [ ]:
X_train = X_train.fillna(0)
X_test  = X_test.fillna(0)

In [ ]:
model_1.fit(X_train, y_train)
pred = model_1.predict(X_test)

accuracy_score(y_test, pred)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_1 = RandomForestClassifier(n_estimators=300, random_state=42)

In [ ]:
model_1.fit(X_train, y_train)
pred = model_1.predict(X_test)
accuracy_score(y_test, pred)

0.7797584818861415

In [ ]:
model_2.fit(X_train, y_train)
pred = model_2.predict(X_test)
accuracy_score(y_test, pred)

0.7251293847038528

In [ ]:
model_3.fit(X_train, y_train)
pred = model_3.predict(X_test)
accuracy_score(y_test, pred)

0.772857964347326

In [ ]:
model_4.fit(X_train, y_train)
pred = model_4.predict(X_test)
accuracy_score(y_test, pred)

0.7843588269120184

In [ ]:
model_5.fit(X_train, y_train)
pred = model_5.predict(X_test)
accuracy_score(y_test, pred)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 3500, number of negative: 3454
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003032 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2147
[LightGBM] [Info] Number of data points in the train set: 6954, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503307 -> initscore=0.013230
[LightGBM] [Info] Start training from score 0.013230

0.7878090856814262

In [ ]:
df.columns

Index(['PassengerId', 'CryoSleep', 'Age', 'VIP', 'RoomService', 'FoodCourt',
       'ShoppingMall', 'Spa', 'VRDeck', 'Transported', 'Deck', 'Num', 'Side',
       'HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars',
       'HomePlanet_U', 'Destination_55 Cancri e', 'Destination_PSO J318.5-22',
       'Destination_TRAPPIST-1e', 'Destination_U', 'am_spent',
       'standard_spent', 'mean_spent'],
      dtype='object')

In [ ]:
ids = df_test['PassengerId']  # save for final submission
X_test = df_test.drop(columns=['PassengerId'])

In [ ]:
# Convert True/False strings to 1/0
bool_cols = ['CryoSleep', 'VIP']
for col in bool_cols:
    X_test[col] = X_test[col].map({'True':1, 'False':0})

# Convert Num to numeric
X_test['Num'] = pd.to_numeric(X_test['Num'], errors='coerce').fillna(-1)

In [ ]:
# Ensure X_test has exactly same columns as X_train used for model_5
X_test = X_test[X_train.columns]

In [ ]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [ ]:
pred = model_5.predict(X_test)

In [ ]:
df_test = pd.read_csv('SpaecShip_Titanic_test.csv')
ids = df_test['PassengerId']
df_test = df_test.drop('PassengerId', axis=1)

# Missing values
df_test.fillna(0, inplace=True)

# Encoding (example)
df_test = pd.get_dummies(df_test)

In [ ]:
df_test = df_test.reindex(columns=X_train.columns, fill_value=0)

In [ ]:
pred = model_5.predict(df_test)

In [ ]:
final = pd.DataFrame({
    'PassengerId': ids,
    'Transported': pred
})

final.to_csv('submission.csv', index=False)

In [ ]:
final = pd.DataFrame()
final['PassengerId'] = ids
final['Transported'] = pred
final.to_csv('submission.csv', index=False)

In [ ]:
df_dumy = pd.read_csv('SpaecShip_Titanic_test.csv')
pred = model_5.predict(df_test)
final = pd.DataFrame()
final['PassengerId'] = df_test['PassengerId']
final['Transported'] = pred
# final.to_csv('sumbissiion.csv', index=False)

In [ ]:
# 1️⃣ Test data load
df_test = pd.read_csv('SpaecShip_Titanic_test.csv')

# 2️⃣ PassengerId alag save
ids = df_test['PassengerId']

# 3️⃣ Model input se PassengerId drop
df_test = df_test.drop('PassengerId', axis=1)

# ⚠️ Yahan wohi preprocessing ho jo training mein thi
df_test.fillna(0, inplace=True)
df_test = pd.get_dummies(df_test)
df_test = df_test.reindex(columns=X_train.columns, fill_value=0)

# 4️⃣ Prediction
pred = model_5.predict(df_test)

# 5️⃣ Kaggle ke liye Boolean
pred = pred.astype(bool)

# 6️⃣ Submission file
final = pd.DataFrame({
    'PassengerId': ids,
    'Transported': pred
})

# 7️⃣ CSV save
final.to_csv('submission_1.csv', index=False)

print(final.shape)
print(final.head())

(4277, 2)
  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True